//! # D-Bus interface proxy for: `org.freedesktop.timedate1`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `Interface '/org/freedesktop/timedate1' from service 'org.freedesktop.timedate1' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PeerProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,

use crate::interfaces::TimeDateInterface;
use async_trait::async_trait;
use log::error;
use zbus::proxy;

#[derive(Debug, Clone, thiserror::Error)]
#[non_exhaustive]
pub enum ProxyError {
    /// Indicates that a D-Bus method call failed.
    #[error("dbus call failed: {0}")]
    DbusCallFailed(String),
}

/// # Security
/// The interactive boolean parameters can be used to control whether
/// polkit should interactively ask the user for authentication
/// credentials if required.
///
/// The polkit action for SetTimezone() is
/// org.freedesktop.timedate1.set-timezone. For SetLocalRTC() it is
/// org.freedesktop.timedate1.set-local-rtc, for SetTime() it is
/// org.freedesktop.timedate1.set-time and for SetNTP() it is
/// org.freedesktop.timedate1.set-ntp.  ListTimezones() does not
/// require any privileges.
#[proxy(
    interface = "org.freedesktop.timedate1",
    default_service = "org.freedesktop.timedate1",
    default_path = "/org/freedesktop/timedate1"
)]
pub trait timedate1 {
    /// Returns a list of time zones known on the local
    ///  system as an array of names ("["Africa/Abidjan", "Africa/Accra",
    ///  ..., "UTC"]").
    fn list_timezones(&self) -> zbus::Result<Vec<String>>;

    /// To control whether the RTC is in local time or
    /// UTC. It is strongly recommended to maintain the RTC in UTC.
    /// However, some OSes (Windows) maintain the RTC in local time, which
    /// might make it necessary to enable this feature. Note that this
    /// might create various problems as daylight changes could be missed.
    /// If fix_system is "true", the time from the RTC is read again and
    /// the system clock is adjusted according to the new setting. If
    /// fix_system is "false", the system time is written to the RTC
    /// taking the new setting into account. Use fix_system=true in
    /// installers and livecds where the RTC is probably more reliable
    /// than the system time. Use fix_system=false in configuration UIs
    /// that are run during normal operation and where the system clock is
    /// probably more reliable than the RTC.
    #[zbus(name = "SetLocalRTC")]
    fn set_local_rtc(
        &self,
        local_rtc: bool,
        fix_system: bool,
        interactive: bool,
    ) -> zbus::Result<()>;

    /// To control whether the system clock is synchronized
    /// with the network using systemd-timesyncd. This will enable and
    /// start or disable and stop the chosen time synchronization service.
    #[zbus(name = "SetNTP")]
    fn set_ntp(&self, use_ntp: bool, interactive: bool) -> zbus::Result<()>;

    /// To change the system clock. Pass a value of
    /// microseconds since the UNIX epoch (1 Jan 1970 UTC). If relative is
    /// true, the passed usec value will be added to the current system
    /// time. If it is false, the current system time will be set to the
    /// passed usec value. If the system time is set with this method, the
    /// RTC will be updated as well.
    fn set_time(&self, usec_utc: i64, relative: bool, interactive: bool) -> zbus::Result<()>;

    /// To set the system timezone. Pass a value like
    /// "Europe/Berlin" to set the timezone. Valid timezones are listed in
    /// /usr/share/zoneinfo/zone.tab. If the RTC is configured to be
    /// maintained in local time, it will be updated accordingly.
    fn set_timezone(&self, timezone: &str, interactive: bool) -> zbus::Result<()>;

    /// CanNTP property
    #[zbus(property, name = "CanNTP")]
    fn can_ntp(&self) -> zbus::Result<bool>;

    /// LocalRTC property
    #[zbus(property, name = "LocalRTC")]
    fn local_rtc(&self) -> zbus::Result<bool>;

    /// NTP property
    #[zbus(property, name = "NTP")]
    fn ntp(&self) -> zbus::Result<bool>;

    /// NTPSynchronized property
    #[zbus(property, name = "NTPSynchronized")]
    fn ntpsynchronized(&self) -> zbus::Result<bool>;

    /// RTCTimeUSec property
    #[zbus(property, name = "RTCTimeUSec")]
    fn rtctime_usec(&self) -> zbus::Result<u64>;

    /// TimeUSec property
    #[zbus(property, name = "TimeUSec")]
    fn time_usec(&self) -> zbus::Result<u64>;

    /// Timezone property
    #[zbus(property)]
    fn timezone(&self) -> zbus::Result<String>;
}

#[async_trait]
impl<'a> TimeDateInterface for timedate1Proxy<'a> {
    async fn list_time_zones(&self) -> anyhow::Result<Vec<String>, ProxyError> {
        match self.list_timezones().await {
            Ok(timezones) => Ok(timezones),
            Err(e) => {
                error!("failed to list timezones: {}", e);
                Err(ProxyError::DbusCallFailed(format!(
                    "failed to list timezones: {}",
                    e
                )))
            }
        }
    }

    async fn set_local_rtc(
        &self,
        local_rtc: bool,
        fix_system: bool,
        interactive: bool,
    ) -> anyhow::Result<(), ProxyError> {
       match self
            .set_local_rtc(local_rtc, fix_system, interactive)
            .await
        {
            Ok(_) => Ok(()),
            Err(e) => {
                error!("failed to set local RTC: {}", e);
                Err(ProxyError::DbusCallFailed(format!(
                    "failed to set local RTC: {}",
                    e
                )))
            }
        }
    }

    async fn set_ntp(&self, use_ntp: bool, interactive: bool) -> anyhow::Result<(), ProxyError> {
        match self.set_ntp(use_ntp, interactive).await {
            Ok(_) => Ok(()),
            Err(e) => {
                error!("failed to set NTP: {}", e);
                Err(ProxyError::DbusCallFailed(format!(
                    "failed to set NTP: {}",
                    e
                )))
            }
        }
    }

    async fn set_time(
        &self,
        usec_utc: i64,
        relative: bool,
        interactive: bool,
    ) -> anyhow::Result<(), ProxyError> {
        match self.set_time(usec_utc, relative, interactive).await {
            Ok(_) => Ok(()),
            Err(e) => {
                error!("failed to set time: {}", e);
                Err(ProxyError::DbusCallFailed(format!(
                    "failed to set time: {}",
                    e
                )))
            }
        }
    }

    async fn set_timezone(
        &self,
        timezone: &str,
        interactive: bool,
    ) -> anyhow::Result<(), ProxyError> {
        match self.set_timezone(timezone, interactive).await {
            Ok(_) => Ok(()),
            Err(e) => {
                error!("failed to set timezone: {}", e);
                Err(ProxyError::DbusCallFailed(format!(
                    "failed to set timezone: {}",
                    e
                )))
            }
        }
    }

    async fn get_timezone(&self) -> anyhow::Result<String, ProxyError> {
        match self.timezone().await {
            Ok(tz) => Ok(tz),
            Err(e) => {
                error!("failed to get timezone: {}", e);
                Err(ProxyError::DbusCallFailed(format!(
                    "failed to get timezone: {}",
                    e
                )))
            }
        }
    }

    async fn get_time_usec(&self) -> anyhow::Result<u64, ProxyError> {
        match self.time_usec().await {
            Ok(time_usec) => Ok(time_usec),
            Err(e) => {
                error!("failed to get time in usec: {}", e);
                Err(ProxyError::DbusCallFailed(format!(
                    "failed to get time in usec: {}",
                    e
                )))
            }
        }
    }
}
