[package]
name = "custom_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relm4 = "0.7.0-beta.1"
relm4-components = "0.7.0-beta.1"
relm4-macros = "0.7.0-beta.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
custom_widgets = { path = "../custom_widgets"}