[package]
name = "session_services"
description = "Service for running session services"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true
version = "0.1.1"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
env_logger = { workspace = true }
thiserror = { workspace = true }
serde  = { workspace = true }
futures = { workspace = true, features = ["thread-pool"] }
zbus = { version = "5.7.1" }
gdk-pixbuf = "0.20.10"
glib = "0.20.12"
zvariant = "5.5.3"
futures-util = "0.3.28"
freedesktop-icons = "0.4.0"
serde_json = "1.0.145"
sled = "0.34.7"
uuid = { version = "1.19.0", features = ["v4"]}

[[bin]]
name = "mechanix_session_services"
path = "src/main.rs"

[package.metadata.deb]
maintainer = "Minesh Purohit <mineshp@mechasystems.com>"
extended-description = """\
Service for running session services."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    # target/release path is special, and gets replaced by cargo-deb with the actual target dir path.
    [
        "../../target/release/mechanix_session_services",
        "usr/bin/",
        "755",
    ],
]
