[package]
name = "mechanix-session-services"
description = "Service for running session services"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]


[package.metadata.deb]
maintainer = "Aksha Raina <akshar@mechasystems.com>"
extended-description = """\
Service for running session services."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    # target/release path is special, and gets replaced by cargo-deb with the actual target dir path.
    [
        "../../target/release/mechanix-session-services",
        "usr/bin/",
        "755",
    ],
]
