[package]
name = "session_service"
description = "Service for running session services"
version = "0.0.2"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
env_logger = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
futures = { workspace = true, features = ["thread-pool"] }
zbus = { version = "5.7.1" }
gdk-pixbuf = "0.20.10"
glib = "0.20.12"
zvariant = "5.5.3"
futures-util = "0.3.28"
freedesktop-icons = "0.4.0"
serde_json = "1.0.145"
sled = "0.34.7"
uuid = { version = "1.19.0", features = ["v4"] }

[[bin]]
name = "mechanix-session-service"
path = "src/main.rs"

[package.metadata.deb]
maintainer = "Minesh Purohit <mineshp@mechasystems.com>"
extended-description = """\
Service for running session services."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    # target/release path is special, and gets replaced by cargo-deb with the actual target dir path.
    [
        "../../target/release/mechanix-session-service",
        "usr/bin/",
        "755",
    ],
    [
        "../desktop/systemd.service",
        "/etc/systemd/user/mechanix-session-service.service",
        "755",
    ],
]

[package.metadata.generate-rpm]
summary = "Service for running session services"
license = "MIT" # or workspace override if you have one
auto-req = "yes"
assets = [
    # Binary
    { source = "../../target/release/mechanix-session-service", dest = "/usr/bin/mechanix-session-service", mode = "755" },
    { source = "../desktop/systemd.service", dest = "/usr/lib/systemd/user/mechanix-session-service.service", mode = "644" },
]
