[package]
name = "mechanix-polkit-agent"
description = "Polkit authentication agent component for the Mechanix shell"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
