
[package]
name = "running_apps"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
gpui = { workspace = true }
rust-embed = { workspace = true }
anyhow = { workspace = true }
commons = { path = "../commons" }
serde = { version = "1.0.163", features = ["derive"] }
xdg = "2.4.1"
wayland-protocols-async = { git = "https://github.com/mecha-org/wayland-protocols-async.git", rev = "0c2c8f6ab9d944e24fdff89f08fd8fe6a67eb6d3" }
tokio = { version = "1.33", features = ["full"] }
tracing = "0.1"
indexmap = "2.1.0"
futures = "0.3.30"
lazy_static = "1.5.0"
notify = "7.0.0"
async-channel = "2.5.0"
