
[package]
name = "running_apps"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
gpui = { workspace = true }
rust-embed = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
commons = { path = "../commons" }
tokio = { workspace = true }
futures = { workspace = true }
notify = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
wayland-protocols-async = { git = "https://github.com/mecha-org/wayland-protocols-async.git", rev = "0c2c8f6ab9d944e24fdff89f08fd8fe6a67eb6d3" }
indexmap = "2.1.0"
lazy_static = "1.5.0"
xdg = "2.4.1"
settings = { path = "../settings" }
theme = { path = "../theme" }
dispatcher = { path = "../dispatcher" }
