//! # D-Bus interface proxy for: `org.mechanix.NotificationManager`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `Interface '/org/mechanix/NotificationManager' from service 'org.mechanix.NotificationManager' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PeerProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
//!
use zbus::proxy;
use crate::notification::Notification;
use std::collections::HashMap;

#[proxy(
    interface = "org.mechanix.NotificationManager",
    default_service = "org.mechanix.NotificationManager",
    default_path = "/org/mechanix/NotificationManager"
)]
pub trait MechanixNotification {
    /// CloseNotificationWithReason method
    fn close_notification_with_reason(&self, id: u32, reason: u32) -> zbus::Result<()>;

    /// GetAllNotifications method
    fn get_all_notifications(&self) -> zbus::Result<HashMap<u32, Notification>>;

    /// GetVersion method
    fn get_version(&self) -> zbus::Result<String>;

    /// InvokeAction method
    fn invoke_action(&self, id: u32, action_key: &str) -> zbus::Result<()>;

    /// SendActivationToken method
    fn send_activation_token(&self, id: u32, activation_token: &str) -> zbus::Result<()>;

    /// NotificationClosed signal
    #[zbus(signal)]
    fn notification_closed(&self, id: u32) -> zbus::Result<()>;

    /// NotificationReceived signal - using clean Notification struct
    #[zbus(signal)]
    fn notification_received(&self, id: u32, notification: Notification) -> zbus::Result<()>;
}