[package]
name = "mechanix-launcher"
description = "Mechanix launcher component for the Mechanix shell"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.0-dev" }
bevy_styled_widgets = { git = "https://github.com/akshayr-mecha/bevy_mctk.git", rev = "71a6c2ef2885adef1d6d8adf238850bb85ebfe59"}
bevy_asset_loader = { version = "0.23.0-rc.3", features = ["standard_dynamic_assets"]}
bevy_core_widgets = { git = "https://github.com/akshayr-mecha/bevy_core_widgets.git",  rev = "24966adefc4494815b9d71bc2bf5814e715f6b43" }
chrono = { version = "0.4", features = ["clock"] }
bevy_smithay = { git = "https://github.com/namana-mecha/bevy_smithay.git", rev = "25680f41d9378464bac315d7f9b262008555154a" }
bevy_plugins = { path = "../../commons/bevy_plugins" }
freedesktop-desktop-entry = "0.7.13"
freedesktop-icons = "0.4.0"
shlex = "1.3.0"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
