
[package]
name = "universal_search"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
gpui = { workspace = true }
rust-embed = { workspace = true }
anyhow = { workspace = true }
commons = { path = "../commons" }
mxsearch = { path = "../../../services/search/server" }
settings = { path = "../settings" }
theme = { path = "../theme" }
unicode-segmentation = "1.12.0"
freedesktop-icons = "0.4.0"