[package]
name = "mechanix-bluetooth-ctl"
description = "Bluetooth controller for Mechanix services"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
bluer = { version = "0.17.1", features = ["full"] }
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3.30"
