[preferred]
org.freedesktop.impl.portal.FileChooser=mechanix;
org.freedesktop.impl.portal.Settings=mechanix;
org.freedesktop.impl.portal.Wallpaper=mechanix;
org.freedesktop.impl.portal.Notification=mechanix;
org.freedesktop.impl.portal.Access=mechanix;
default=gnome;gtk;
