[package]
name = "volume_slider"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
gpui = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
log = { workspace = true }
zbus = { workspace = true }
power_options = { path = "../power_options" }
shell_state = { path = "../shell_state" }
settings = { path = "../settings" }
dispatcher = { path = "../dispatcher" }
futures-util = "0.3.31"
icons = { path = "../icons" }
