[package]
name = "mechanix_network_ctl"
description = "Network controller for Mechanix services"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "io-std", "io-util"] }
tokio-util  ={ version = "0", features = ["codec"] }
futures = "0"
mockall = "0.11.4"