
[package]
name = "commons"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
gpui = { workspace = true }
rust-embed = { workspace = true }
anyhow = { workspace = true }
toml = { workspace = true }
rand = "0.8"
unicode-segmentation = "1.12.0"

[[example]]
name = "wing"
path = "examples/wing.rs"

[[example]]
name = "animated_wing"
path = "examples/animated_wing.rs"

[[example]]
name = "wing_with_children"
path = "examples/wing_with_children.rs"
