
[package]
name = "theme"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
gpui = { workspace = true }
palette = { version = "0.7.6", features = ["serializing"] }
dispatcher = { path = "../dispatcher" }
futures = { workspace = true }
mxconf_dbus = { workspace = true }
