[workspace]
resolver = "2"
members = [
    "freedesktop/network-manager/freedesktop-network-manager-client", "freedesktop/upower/freedesktop-upower-client", "freedesktop/bluez/freedesktop-bluez-client", "freedesktop/pulseaudio/freedesktop-pulseaudio-client",
]
default-members = ["freedesktop/network-manager/freedesktop-network-manager-client"]


[workspace.package]
version = "0.1.0"
authors = [
    "Dhruvesh Baria <dhruveshb@mechasystems.com>",
    "Shoaib Merchant <shoaibm@mechasystems.com>",
    "Minesh Purohit <mineshp@mechasystems.com>",
]
edition = "2021"
license = "MIT"
repository = "https://github.com/mecha-org/mechanix-gui"
homepage = "https://mecha.so"
categories = ["gui"]
keywords = [
    "linux",
    "shell",
    "gui",
    "interface",
    "widgets",
]

[workspace.dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
zbus = { version = "5.7.1" }
futures = "0.3.30"
thiserror = { version = "2.0.12" }
async-trait = { version = "0.1.88" }
log = { version = "0.4.27" }
mockall = { version = "0.13.1" }
