[package]
name = "animation"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
bevy = { workspace = true }
bevy_time_runner = { version = "0.4.1" }
bevy_tween_helpers = { version = "0.1.4" }
