[package]
name = "mechanix-system-service"
description = "Service for running system services"
version = "0.0.2"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
anyhow = { workspace = true }
zbus = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
env_logger = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
mechanix-hw-buttons = { path = "../../shared/hw-buttons" }

[package.metadata.deb]
maintainer = "Minesh Purohit <mineshp@mechasystems.com>"
extended-description = """\
Service for running system services."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    # target/release path is special, and gets replaced by cargo-deb with the actual target dir path.
    [
        "../../target/release/mechanix-system-service",
        "/usr/bin/",
        "755",
    ],
    [
        "../system/system-dbus.conf",
        "/etc/dbus-1/system.d/system-dbus.conf",
        "644",
    ],
    [
        "../system/systemd.service",
        "/etc/systemd/system/mechanix-system-service.service",
        "644",
    ],
]

[package.metadata.generate-rpm]
summary = "Service for running system services"
license = "MIT" # or workspace override if you have one
auto-req = "yes"
assets = [
    # Binary
    { source = "../../target/release/mechanix-system-service", dest = "/usr/bin/mechanix-system-service", mode = "755" },
    { source = "../system/system-dbus.conf", dest = "/etc/dbus-1/system.d/system-dbus.conf", mode = "644" },
    { source = "../system/systemd.service", dest = "/usr/lib/systemd/system/mechanix-system-service.service", mode = "644" },

]
