[package]
name = "networkmanager"
documentation = "https://docs.mecha.so"
version = "1.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/mecha-org/mechanix-gui"
homepage = "https://mecha.so"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.33", features = ["full"] }
zbus = { version = "4.1.2", features = ["tokio"] }
serde = { version = "1.0.163", features = ["derive"] }
uuid = "1.11.0"
anyhow = "1"
mctk_core = { git = "https://github.com/mecha-org/mctk.git", rev = "d59490c6391d9e0623b2658d3e95e4b7e030634b" }
mctk_macros = { git = "https://github.com/mecha-org/mctk.git", rev = "d59490c6391d9e0623b2658d3e95e4b7e030634b" }
futures = "0.3.30"
lazy_static = "1.5.0"
