[package]
name = "mechanix_system_dbus_client"
description = "Zbus client for Mechanix zbus services"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
anyhow.workspace = true
zbus.workspace = true
tracing.workspace = true
serde.workspace = true
mechanix_system_dbus_server = { path = "../../server/dbus" }
policykit.workspace = true