import 'package:mechanix_settings/src/features/settings_menu/models/types.dart';

final Map<String, RouteMeta> routeMetaMap = {
  '/wireless': RouteMeta(backTitle: 'Settings'),
  '/wireless/network_details': RouteMeta(backTitle: 'Network'),
  '/wireless/network_settings': RouteMeta(backTitle: 'Network'),
  '/wireless/connect_secure_network': RouteMeta(backTitle: 'Network'),
  '/wireless/add_network': RouteMeta(backTitle: 'Network'),
  '/wireless/ip': RouteMeta(backTitle: 'Network'),
  '/wireless/ethernet': RouteMeta(backTitle: 'Network'),
  '/wireless/dns': RouteMeta(backTitle: 'Network'),
  '/bluetooth': RouteMeta(backTitle: 'Settings'),
  '/bluetooth/info': RouteMeta(backTitle: 'Bluetooth'),
  '/bluetooth/settings': RouteMeta(backTitle: 'Bluetooth'),
  '/bluetooth/settings/rename': RouteMeta(backTitle: 'Adapter Settings'),
  '/battery': RouteMeta(backTitle: 'Settings'),
  '/battery/performance': RouteMeta(backTitle: 'Battery'),
  '/display': RouteMeta(backTitle: 'Settings'),
  '/display/screen_offtime': RouteMeta(backTitle: 'Display'),
  '/sound': RouteMeta(backTitle: 'Settings'),
  '/sound/output_devices': RouteMeta(backTitle: 'Sound'),
  '/sound/input_devices': RouteMeta(backTitle: 'Sound'),
  '/about': RouteMeta(backTitle: 'Settings'),
  '/date_time': RouteMeta(backTitle: 'Settings'),
  '/date_time/time_settings': RouteMeta(backTitle: 'Date & Time'),
  '/date_time/date_settings': RouteMeta(backTitle: 'Date & Time'),
  '/appearance': RouteMeta(backTitle: 'Settings'),
  '/appearance/apply_wallpaper': RouteMeta(backTitle: 'Appearance'),
};
