[app_drawer]
"category" = "assets/icons/app-drawer/category.png"
"default-app" = "assets/icons/app-drawer/default-app.png"
"delete" = "assets/icons/app-drawer/delete.svg"
"info" = "assets/icons/app-drawer/info.svg"
"search" = "assets/icons/app-drawer/search.svg"
"x" = "assets/icons/app-drawer/x.png"

[keyboard]
"backspace" = "assets/icons/keyboard/backspace.svg"
"shift" = "assets/icons/keyboard/shift.svg"

[notifications]
"application" = "assets/icons/notifications/application.svg"
"info" = "assets/icons/notifications/info.svg"
"close" = "assets/icons/notifications/close.svg"
"navbar-gray" = "assets/icons/notifications/navbar-gray.png"
"navbar" = "assets/icons/notifications/navbar.png"
"bell" = "assets/icons/notifications/bell.svg"

[power_options]
"down-arrow" = "assets/icons/power-options/down-arrow.svg"
"power-off" = "assets/icons/power-options/power-off.svg"

[running_apps]
"cleanup" = "assets/icons/running-apps/cleanup.svg"

[lockscreen]
"arrow" = "assets/icons/lockscreen/arrow.svg"
"bell" = "assets/icons/lockscreen/bell.svg"
"lock" = "assets/icons/lockscreen/lock.svg"
"lock-open-full" = "assets/icons/lockscreen/lock-open-full.svg"
"lock-open-half" = "assets/icons/lockscreen/lock-open-half.svg"
"wedge-left" = "assets/icons/lockscreen/wedge-left.svg"
"wedge-left-outline" = "assets/icons/lockscreen/wedge-left-outline.svg"
"wedge-right" = "assets/icons/lockscreen/wedge-right.svg"
"wedge-right-outline" = "assets/icons/lockscreen/wedge-right-outline.svg"
"wallpaper" = "assets/icons/lockscreen/wallpaper.png"

[settings_drawer]
"airplane" = "assets/icons/settings-drawer/airplane.svg"
"auto-brightness" = "assets/icons/settings-drawer/auto-brightness.svg"
"bluetooth-connected" = "assets/icons/settings-drawer/bluetooth-connected.svg"
"bluetooth-off" = "assets/icons/settings-drawer/bluetooth-off.svg"
"bluetooth-on" = "assets/icons/settings-drawer/bluetooth-on.svg"
"brightness-high" = "assets/icons/settings-drawer/brightness-high.svg"
"brightness-low" = "assets/icons/settings-drawer/brightness-low.svg"
"brightness-medium" = "assets/icons/settings-drawer/brightness-medium.svg"
"camera-off" = "assets/icons/settings-drawer/camera-off.svg"
"camera-on" = "assets/icons/settings-drawer/camera-on.svg"
"cell-signal-high" = "assets/icons/settings-drawer/cell-signal-high.svg"
"cell-signal-none" = "assets/icons/settings-drawer/cell-signal-none.svg"
"cell-signal-warning" = "assets/icons/settings-drawer/cell-signal-warning.svg"
"connected-wireless-high-locked" = "assets/icons/settings-drawer/connected-wireless-high-locked.svg"
"connected-wireless-high" = "assets/icons/settings-drawer/connected-wireless-high.svg"
"connected-wireless-low-locked" = "assets/icons/settings-drawer/connected-wireless-low-locked.svg"
"connected-wireless-low" = "assets/icons/settings-drawer/connected-wireless-low.svg"
"connected-wireless-medium-locked" = "assets/icons/settings-drawer/connected-wireless-medium-locked.svg"
"connected-wireless-medium" = "assets/icons/settings-drawer/connected-wireless-medium.svg"
"connected-wireless-on" = "assets/icons/settings-drawer/connected-wireless-on.svg"
"connected-wireless-warning" = "assets/icons/settings-drawer/connected-wireless-warning.svg"
"connected" = "assets/icons/settings-drawer/connected.svg"
"dark-mode" = "assets/icons/settings-drawer/dark-mode.svg"
"extended-detected" = "assets/icons/settings-drawer/extended-detected.svg"
"extended-only" = "assets/icons/settings-drawer/extended-only.svg"
"external-speaker" = "assets/icons/settings-drawer/external-speaker.svg"
"gray-dot-grid" = "assets/icons/settings-drawer/gray-dot-grid.png"
"headphone" = "assets/icons/settings-drawer/headphone.svg"
"high-performance" = "assets/icons/settings-drawer/high-performance.svg"
"low-performance" = "assets/icons/settings-drawer/low-performance.svg"
"microphone-off" = "assets/icons/settings-drawer/microphone-off.svg"
"microphone-on" = "assets/icons/settings-drawer/microphone-on.svg"
"mirror-screen" = "assets/icons/settings-drawer/mirror-screen.svg"
"navbar-gray" = "assets/icons/settings-drawer/navbar-gray.png"
"navbar" = "assets/icons/settings-drawer/navbar.png"
"power-mode-balanced" = "assets/icons/settings-drawer/power-mode-balanced.svg"
"power-mode-high" = "assets/icons/settings-drawer/power-mode-high.svg"
"power-mode-low" = "assets/icons/settings-drawer/power-mode-low.svg"
"power-off" = "assets/icons/settings-drawer/power-off.svg"
"rotation-off" = "assets/icons/settings-drawer/rotation-off.svg"
"rotation-on" = "assets/icons/settings-drawer/rotation-on.svg"
"screen-mirroring-off" = "assets/icons/settings-drawer/screen-mirroring-off.svg"
"screen-mirroring-on" = "assets/icons/settings-drawer/screen-mirroring-on.svg"
"screen-recording-off" = "assets/icons/settings-drawer/screen-recording-off.svg"
"screen-recording-on" = "assets/icons/settings-drawer/screen-recording-on.svg"
"second-screen" = "assets/icons/settings-drawer/second-screen.svg"
"settings" = "assets/icons/settings-drawer/settings.svg"
"slider-gray-dot-column" = "assets/icons/settings-drawer/slider-gray-dot-column.svg"
"slider-orange-dot-column" = "assets/icons/settings-drawer/slider-orange-dot-column.png"
"slider-accent-dots-column" = "assets/icons/settings-drawer/slider-accent-dots-column.svg"
"system-speaker" = "assets/icons/settings-drawer/system-speaker.svg"
"terminal" = "assets/icons/settings-drawer/terminal.svg"
"volume-high" = "assets/icons/settings-drawer/volume-high.svg"
"volume-low" = "assets/icons/settings-drawer/volume-low.svg"
"volume-medium" = "assets/icons/settings-drawer/volume-medium.svg"
"volume-off" = "assets/icons/settings-drawer/volume-off.svg"
"wireless-high-locked" = "assets/icons/settings-drawer/wireless-high-locked.svg"
"wireless-high" = "assets/icons/settings-drawer/wireless-high.svg"
"wireless-low-locked" = "assets/icons/settings-drawer/wireless-low-locked.svg"
"wireless-low" = "assets/icons/settings-drawer/wireless-low.svg"
"wireless-medium-locked" = "assets/icons/settings-drawer/wireless-medium-locked.svg"
"wireless-medium" = "assets/icons/settings-drawer/wireless-medium.svg"
"wireless-none" = "assets/icons/settings-drawer/wireless-none.svg"
"wireless-off" = "assets/icons/settings-drawer/wireless-off.svg"
"wireless-warning" = "assets/icons/settings-drawer/wireless-warning.svg"

[status_bar]
"battery-0-charging" = "assets/icons/status-bar/battery-0-charging.svg"
"battery-10-charging" = "assets/icons/status-bar/battery-10-charging.svg"
"battery-10" = "assets/icons/status-bar/battery-10.svg"
"battery-100-charging" = "assets/icons/status-bar/battery-100-charging.svg"
"battery-100" = "assets/icons/status-bar/battery-100.svg"
"battery-20-charging" = "assets/icons/status-bar/battery-20-charging.svg"
"battery-20" = "assets/icons/status-bar/battery-20.svg"
"battery-30-charging" = "assets/icons/status-bar/battery-30-charging.svg"
"battery-30" = "assets/icons/status-bar/battery-30.svg"
"battery-40-charging" = "assets/icons/status-bar/battery-40-charging.svg"
"battery-40" = "assets/icons/status-bar/battery-40.svg"
"battery-50-charging" = "assets/icons/status-bar/battery-50-charging.svg"
"battery-50" = "assets/icons/status-bar/battery-50.svg"
"battery-60-charging" = "assets/icons/status-bar/battery-60-charging.svg"
"battery-60" = "assets/icons/status-bar/battery-60.svg"
"battery-70-charging" = "assets/icons/status-bar/battery-70-charging.svg"
"battery-70" = "assets/icons/status-bar/battery-70.svg"
"battery-80-charging" = "assets/icons/status-bar/battery-80-charging.svg"
"battery-80" = "assets/icons/status-bar/battery-80.svg"
"battery-90-charging" = "assets/icons/status-bar/battery-90-charging.svg"
"battery-90" = "assets/icons/status-bar/battery-90.svg"
"battery-empty" = "assets/icons/status-bar/battery-empty.svg"
"bluetooth-connected" = "assets/icons/status-bar/bluetooth-connected.svg"
"bluetooth-off" = "assets/icons/status-bar/bluetooth-off.svg"
"bluetooth-on" = "assets/icons/status-bar/bluetooth-on.svg"
"bluetooth-warning" = "assets/icons/status-bar/bluetooth-warning.svg"
"wireless-high" = "assets/icons/status-bar/wireless-high.svg"
"wireless-low" = "assets/icons/status-bar/wireless-low.svg"
"wireless-medium" = "assets/icons/status-bar/wireless-medium.svg"
"wireless-off" = "assets/icons/status-bar/wireless-off.svg"
"wireless-on" = "assets/icons/status-bar/wireless-on.svg"
"wireless-warning" = "assets/icons/status-bar/wireless-warning.svg"

[universal_search]
"ardour" = "assets/icons/universal-search/ardour.png"
"arrow-counter-clock-wise" = "assets/icons/universal-search/arrow-counter-clock-wise.svg"
"arrow-up-right" = "assets/icons/universal-search/arrow-up-right.svg"
"audio-file" = "assets/icons/universal-search/audio-file.svg"
"chromium" = "assets/icons/universal-search/chromium.png"
"code-file" = "assets/icons/universal-search/code-file.svg"
"csv-file" = "assets/icons/universal-search/csv-file.svg"
"default-app" = "assets/icons/universal-search/default-app.svg"
"default-file" = "assets/icons/universal-search/default-file.svg"
"default-folder" = "assets/icons/universal-search/default-folder.svg"
"doc-file" = "assets/icons/universal-search/doc-file.svg"
"firefox" = "assets/icons/universal-search/firefox.png"
"github" = "assets/icons/universal-search/github.png"
"image-file" = "assets/icons/universal-search/image-file.svg"
"locked-file" = "assets/icons/universal-search/locked-file.svg"
"navbar" = "assets/icons/universal-search/navbar.png"
"pdf-file" = "assets/icons/universal-search/pdf-file.svg"
"search" = "assets/icons/universal-search/search.svg"
"video-file" = "assets/icons/universal-search/video-file.svg"
"x" = "assets/icons/universal-search/x.svg"
"xls-file" = "assets/icons/universal-search/xls-file.svg"
"zip-file" = "assets/icons/universal-search/zip-file.svg"

[homescreen.extensions]
gamepad = "assets/icons/homescreen/extensions/gamepad.png"
keyboard = "assets/icons/homescreen/extensions/keyboard.png"
gpio = "assets/icons/homescreen/extensions/gpio.png"
unknown = "assets/icons/homescreen/extensions/unknown.png"
dot-grid = "assets/icons/homescreen/extensions/dot-grid.png"
detached = "assets/icons/homescreen/extensions/detached.png"

[homescreen.clock]
dashed = "assets/icons/homescreen/clock/dashed.png"

[toast]
extension-attached = "assets/icons/toast/extension_attached.png"
extension-detached = "assets/icons/toast/extension_detached.png"
close = "assets/icons/toast/cross.png"
