[status_bar.layer_shell]
layer = "overlay"
anchor = ["right", "left", "top"]
namespace = "mechanix.status.bar"
exclusive_zone = 0.0
size = { width = 540.0, height = 180.0 }

[settings_drawer]
navbar_size = { width = 199.22, height = 28.5 }

[settings_drawer.layer_shell]
layer = "top"
anchor = ["bottom"]
namespace = "mechanix.settings.drawer"
exclusive_zone = -1.0
size = { width = 540.0, height = 620.0 }

[settings_drawer.input_regions]
minimized = { origin = { x = 310.0, y = 591.0 }, size = { width = 230.0, height = 100.0 } }
maximized = { origin = { x = 0.0, y = 0.0 }, size = { width = 540.0, height = 620.0 } }


[notifications]
navbar_size = { width = 199.22, height = 28.5 }

[notifications.layer_shell]
layer = "top"
anchor = ["bottom"]
namespace = "mechanix.notifications"
exclusive_zone = -1.0
size = { width = 540.0, height = 620.0 }

[notifications.input_regions]
minimized = { origin = { x = 0.0, y = 591.0 }, size = { width = 230.0, height = 100.0 } }
maximized = { origin = { x = 0.0, y = 0.0 }, size = { width = 540.0, height = 620.0 } }

[running_apps]
navbar_size = { width = 80.0, height = 29.0 }

[running_apps.layer_shell]
layer = "top"
anchor = ["top"]
namespace = "mechanix.running.apps"
exclusive_zone = -1.0
size = { width = 540.0, height = 620.0 }

[running_apps.input_regions]
minimized = { origin = { x = 230.0, y = 591.0 }, size = { width = 80.0, height = 100.0 } }
maximized = { origin = { x = 0.0, y = 0.0 }, size = { width = 540.0, height = 620.0 } }


[homescreen]
status_bar_size = { width = 540.0, height = 36.0 }
time_format = "%H:%M"

[homescreen.layer_shell]
layer = "bottom"
anchor = ["top", "left", "right", "bottom"]
namespace = "mechanix.homescreen"
exclusive_zone = 0.0
size = { width = 540.0, height = 591.5 }


[power_options.layer_shell]
layer = "overlay"
anchor = ["top", "left", "right", "bottom"]
namespace = "mechanix.power.options"
exclusive_zone = 0.0
size = { width = 540.0, height = 620.0 }

[lockscreen.layer_shell]
layer = "overlay"
anchor = ["top", "left", "right", "bottom"]
namespace = "mechanix.lockscreen"
exclusive_zone = 0.0
size = { width = 540.0, height = 620.0 }

[lockscreen]
time_format = "%-I:%M %p"
date_format = "%A, %-d %b" 

[lockscreen.input_regions]
maximized = { origin = { x = 0.0, y = 0.0 }, size = { width = 540.0, height = 620.0 } }

[volume_slider.layer_shell]
layer = "overlay"
anchor = ["left"]
namespace = "mechanix.hardware_buttons.slider"
exclusive_zone = 0.0
size = { width = 36.0, height = 276.0 }

[volume_slider]
min_volume_level = 0.0
max_volume_level = 100.0
overlay_timeout_ms = 2000

[volume_slider.input_regions]
maximized = { origin = { x = 0, y = 0 }, size = { width = 36.0, height = 276.0 } }

[launcher.layer_shell]
layer = "bottom"
anchor = ["top", "left", "right", "bottom"]
namespace = "mechanix.launcher"
exclusive_zone = 0.0
size = { width = 540.0, height = 620.0 }

[keyboard]
default_layout = "/usr/share/mechanix/shell/assets/layouts/us.yaml"

[keyboard.layer_shell]
layer = "overlay"
anchor = ["bottom", "left", "right"]
namespace = "mechanix.keyboard"
exclusive_zone = 0.0
size = { width = 540.0, height = 274.0 }

[system_apps]
files = "Mechanix Files"
settings = "Mechanix Settings"
terminal = "Alacritty"
camera = "Mechanix Camera"

[toast]
timeout_ms = 3000

[toast.layer_shell]
layer = "overlay"
anchor = ["top", "left", "right"]
namespace = "mechanix.toast"
exclusive_zone = 0.0
size = { width = 540.0, height = 48.0 }

[toast.input_regions]
maximized = { origin = { x = 91.0, y = 0.0 }, size = { width = 358.0, height = 48.0 } }
