//! # D-Bus interface proxy for: `org.freedesktop.NetworkManager`
//!
//! This code was generated by `zbus-xmlgen` `4.1.0` from D-Bus introspection data.
//! Source: `Interface '/org/freedesktop/NetworkManager' from service 'org.freedesktop.NetworkManager' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,

//! The `proxy` module provides the [`NetworkManagerProxy`] type, which implements the [`NetworkManagerInterface`] trait
//! for interacting with NetworkManager over D-Bus.
//!
//! See [`NetworkManagerInterface`] for available methods.
pub use crate::interfaces::NetworkManagerInterface;
pub mod access_point;
pub mod device;
pub mod wireless;

use std::collections::HashMap;

pub use anyhow::Result;
use async_trait::async_trait;
pub use device as device_proxy;
use log::{error, info, trace};
use uuid::Uuid;
use zbus::{
    Connection, proxy,
    zvariant::{ObjectPath, Value},
};

use super::interfaces::wireless::RawAccessPointInfo;

// Define a constant for WiFi device type (as per NetworkManager specification)
const WIFI_DEVICE_TYPE: u32 = 2;

/// Represents errors that can occur when interacting with D-Bus proxies.
#[derive(Debug, Clone, thiserror::Error)]
pub enum ProxyError {
    /// Indicates that a D-Bus method call failed.
    #[error("dbus call failed: {0}")]
    DbusCallFailed(String),

    /// Indicates that an invalid device path was provided.
    #[error("invalid device path: {0}")]
    InvalidDevicePath(String),

    /// Indicates that a D-Bus proxy creation failed.
    #[error("failed to create proxy: {0}")]
    ProxyCreationFailed(String),

    /// Indicates that a no wifi device found.
    #[error("no wifi device found")]
    NoWifiDeviceFound,
}

#[proxy(
    interface = "org.freedesktop.NetworkManager",
    default_service = "org.freedesktop.NetworkManager",
    default_path = "/org/freedesktop/NetworkManager"
)]
pub trait NetworkManager {
    /// ActivateConnection method
    fn activate_connection(
        &self,
        connection: &zbus::zvariant::ObjectPath<'_>,
        device: &zbus::zvariant::ObjectPath<'_>,
        specific_object: &zbus::zvariant::ObjectPath<'_>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// AddAndActivateConnection method
    fn add_and_activate_connection(
        &self,
        connection: std::collections::HashMap<
            &str,
            std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
        >,
        device: &zbus::zvariant::ObjectPath<'_>,
        specific_object: &zbus::zvariant::ObjectPath<'_>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        zbus::zvariant::OwnedObjectPath,
    )>;

    /// AddAndActivateConnection2 method
    #[allow(clippy::too_many_arguments)]
    fn add_and_activate_connection2(
        &self,
        connection: std::collections::HashMap<
            &str,
            std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
        >,
        device: &zbus::zvariant::ObjectPath<'_>,
        specific_object: &zbus::zvariant::ObjectPath<'_>,
        options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        zbus::zvariant::OwnedObjectPath,
        std::collections::HashMap<String, zbus::zvariant::OwnedValue>,
    )>;

    /// CheckConnectivity method
    fn check_connectivity(&self) -> zbus::Result<u32>;

    /// CheckpointAdjustRollbackTimeout method
    fn checkpoint_adjust_rollback_timeout(
        &self,
        checkpoint: &zbus::zvariant::ObjectPath<'_>,
        add_timeout: u32,
    ) -> zbus::Result<()>;

    /// CheckpointCreate method
    fn checkpoint_create(
        &self,
        devices: &[&zbus::zvariant::ObjectPath<'_>],
        rollback_timeout: u32,
        flags: u32,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// CheckpointDestroy method
    fn checkpoint_destroy(&self, checkpoint: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// CheckpointRollback method
    fn checkpoint_rollback(
        &self,
        checkpoint: &zbus::zvariant::ObjectPath<'_>,
    ) -> zbus::Result<std::collections::HashMap<String, u32>>;

    /// DeactivateConnection method
    fn deactivate_connection(
        &self,
        active_connection: &zbus::zvariant::ObjectPath<'_>,
    ) -> zbus::Result<()>;

    /// Enable method
    fn enable(&self, enable: bool) -> zbus::Result<()>;

    /// GetAllDevices method
    fn get_all_devices(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// GetDeviceByIpIface method
    fn get_device_by_ip_iface(&self, iface: &str) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// GetDevices method
    fn get_devices(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// GetLogging method
    fn get_logging(&self) -> zbus::Result<(String, String)>;

    /// GetPermissions method
    fn get_permissions(&self) -> zbus::Result<std::collections::HashMap<String, String>>;

    /// Reload method
    fn reload(&self, flags: u32) -> zbus::Result<()>;

    /// SetLogging method
    fn set_logging(&self, level: &str, domains: &str) -> zbus::Result<()>;

    /// Sleep method
    fn sleep(&self, sleep: bool) -> zbus::Result<()>;

    /// state method
    // #[zbus(name = "state")]
    // fn state(&self) -> zbus::Result<u32>;

    /// CheckPermissions signal
    #[zbus(signal)]
    fn check_permissions(&self) -> zbus::Result<()>;

    /// DeviceAdded signal
    #[zbus(signal)]
    fn device_added(&self, device_path: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// DeviceRemoved signal
    #[zbus(signal)]
    fn device_removed(&self, device_path: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// StateChanged signal
    // #[zbus(signal)]
    // fn state_changed(&self, state: u32) -> zbus::Result<()>;

    /// ActivatingConnection property
    #[zbus(property)]
    fn activating_connection(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// ActiveConnections property
    #[zbus(property)]
    fn active_connections(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// AllDevices property
    #[zbus(property)]
    fn all_devices(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// Capabilities property
    #[zbus(property)]
    fn capabilities(&self) -> zbus::Result<Vec<u32>>;

    /// Checkpoints property
    #[zbus(property)]
    fn checkpoints(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// Connectivity property
    #[zbus(property)]
    fn connectivity(&self) -> zbus::Result<u32>;

    /// ConnectivityCheckAvailable property
    #[zbus(property)]
    fn connectivity_check_available(&self) -> zbus::Result<bool>;

    /// ConnectivityCheckEnabled property
    #[zbus(property)]
    fn connectivity_check_enabled(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_connectivity_check_enabled(&self, value: bool) -> zbus::Result<()>;

    /// ConnectivityCheckUri property
    #[zbus(property)]
    fn connectivity_check_uri(&self) -> zbus::Result<String>;

    /// Devices property
    #[zbus(property)]
    fn devices(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// GlobalDnsConfiguration property
    #[zbus(property)]
    fn global_dns_configuration(
        &self,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;
    // #[zbus(property)]
    // fn set_global_dns_configuration(
    //     &self,
    //     value: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    // ) -> zbus::Result<()>;

    /// Metered property
    #[zbus(property)]
    fn metered(&self) -> zbus::Result<u32>;

    /// NetworkingEnabled property
    #[zbus(property)]
    fn networking_enabled(&self) -> zbus::Result<bool>;

    /// PrimaryConnection property
    #[zbus(property)]
    fn primary_connection(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// PrimaryConnectionType property
    #[zbus(property)]
    fn primary_connection_type(&self) -> zbus::Result<String>;

    /// RadioFlags property
    #[zbus(property)]
    fn radio_flags(&self) -> zbus::Result<u32>;

    /// Startup property
    #[zbus(property)]
    fn startup(&self) -> zbus::Result<bool>;

    /// State property
    #[zbus(property)]
    fn state(&self) -> zbus::Result<u32>;

    /// Version property
    #[zbus(property)]
    fn version(&self) -> zbus::Result<String>;

    /// VersionInfo property
    #[zbus(property)]
    fn version_info(&self) -> zbus::Result<Vec<u32>>;

    /// WimaxEnabled property
    #[zbus(property)]
    fn wimax_enabled(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_wimax_enabled(&self, value: bool) -> zbus::Result<()>;

    /// WimaxHardwareEnabled property
    #[zbus(property)]
    fn wimax_hardware_enabled(&self) -> zbus::Result<bool>;

    /// WirelessEnabled property
    #[zbus(property)]
    fn wireless_enabled(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_wireless_enabled(&self, value: bool) -> zbus::Result<()>;

    /// WirelessHardwareEnabled property
    #[zbus(property)]
    fn wireless_hardware_enabled(&self) -> zbus::Result<bool>;

    /// WwanEnabled property
    #[zbus(property)]
    fn wwan_enabled(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_wwan_enabled(&self, value: bool) -> zbus::Result<()>;

    /// WwanHardwareEnabled property
    #[zbus(property)]
    fn wwan_hardware_enabled(&self) -> zbus::Result<bool>;
}

/// Macro to handle the result of an async operation and continue on error.
macro_rules! try_property {
    ($expr:expr) => {
        match $expr.await {
            Ok(val) => val,
            Err(_) => continue,
        }
    };
}

// Implement the NetworkManagerInterface trait for NetworkManagerProxy
#[async_trait]
impl<'a> NetworkManagerInterface for NetworkManagerProxy<'a> {
    /// Enable or disable WiFi via NetworkManager.
    async fn enable_wifi(&self) -> Result<(), ProxyError> {
        info!("setting WiFi to true");
        // Call the underlying D-Bus method to set a wireless state.
        match self.set_wireless_enabled(true).await 
        {
            Ok(_) => {
                info!("wifi is set to true");
                Ok(())
            }
            Err(e) => {
                error!("failed to set WiFi: {}", e);
                Err(ProxyError::DbusCallFailed(format!(
                    "failed to set WiFi: {}",
                    e
                )))
            }
        }
    }

    /// Disable wireless via NetworkManager.
    async fn disable_wifi(&self) -> Result<(), ProxyError> {
        info!("setting WiFi to true");
        // Call the underlying D-Bus method to set a wireless state.
        match self.set_wireless_enabled(false).await {
            Ok(_) => {
                info!("wifi is set to true");
                Ok(())
            }
            Err(e) => {
                error!("failed to set WiFi: {}", e);
                Err(ProxyError::DbusCallFailed(format!(
                    "failed to set WiFi: {}",
                    e
                )))
            }
        }
    }

    /// List all available Wireless networks by querying all devices, filtering for wireless networks, and collecting access point info.
    async fn list_networks(&self) -> Result<Vec<RawAccessPointInfo>, ProxyError> {
        info!("listing available WiFi networks...");
        // Fetch all network devices from NetworkManager.
        let devices = match self.get_all_devices().await {
            Ok(devices) => devices,
            Err(e) => {
                error!("failed to get devices: {}", e);
                return Err(ProxyError::DbusCallFailed(format!(
                    "failed to get devices: {}",
                    e
                )));
            }
        };
        trace!("found {} devices", devices.len());
        // Initialize a vector to hold the networks.
        let mut networks = Vec::new();

        // Iterate through each device to find WiFi devices (device_type == WIFI_DEVICE_TYPE).
        for device in devices {
            // Create a proxy for the device.
            let device_proxy =
                match device_proxy::DeviceProxy::new(&self.0.connection(), &device).await {
                    Ok(proxy) => proxy,
                    Err(e) => {
                        error!(
                            "failed to create device proxy for {}, error {}",
                            device,
                            e.to_string()
                        );
                        continue;
                    }
                };

            // Get the device type.
            let device_type = match device_proxy.device_type().await {
                Ok(device_type) => device_type,
                Err(e) => {
                    error!(
                        "failed to get device type for {}, error {}",
                        device,
                        e.to_string()
                    );
                    continue;
                }
            };
            trace!("device type: {}", device_type);

            // Check if the device is a WiFi device.
            if device_type == WIFI_DEVICE_TYPE {
                // Create a proxy for the wireless interface.
                let wireless_proxy =
                    match wireless::WirelessDeviceProxy::new(&self.0.connection(), &device).await {
                        Ok(proxy) => proxy,
                        Err(e) => {
                            error!(
                                "failed to create wireless proxy for {}, error {}",
                                device,
                                e.to_string()
                            );
                            continue;
                        }
                    };

                // Get all access points for this wireless device.
                let access_points = match wireless_proxy.get_all_access_points().await {
                    Ok(access_points) => access_points,
                    Err(e) => {
                        error!(
                            "failed to get access points for {}, error {}",
                            device,
                            e.to_string()
                        );
                        continue;
                    }
                };
                for access_point in access_points {
                    // Create a proxy for the access point.
                    let access_point_proxy = match access_point::AccessPointProxy::new(
                        &self.0.connection(),
                        access_point,
                    )
                    .await
                    {
                        Ok(proxy) => proxy,
                        Err(_) => continue,
                    };

                    // Extract properties from the access point.
                    let ssid_vec = try_property!(access_point_proxy.ssid());
                    let flags = try_property!(access_point_proxy.flags());
                    let frequency = try_property!(access_point_proxy.frequency());
                    let bandwidth = try_property!(access_point_proxy.bandwidth());
                    let signal_strength = try_property!(access_point_proxy.strength());
                    let hw_address = try_property!(access_point_proxy.hw_address());

                    // Build the access point info struct.
                    let raw_access_point_info = RawAccessPointInfo {
                        ssid: ssid_vec,
                        flags,
                        frequency,
                        bandwidth,
                        strength: signal_strength,
                        hw_address,
                        ..Default::default()
                    };
                    networks.push(raw_access_point_info);
                }
            }
        }
        Ok(networks)
    }

    /// Attempt to connect to a WiFi network with the given SSID and optional password.
    async fn connect_to_network(
        &self,
        ssid: &str,
        password: Option<String>,
    ) -> Result<(String, String), ProxyError> {
        info!("connecting to network: {}", ssid);
        let cn = self.0.connection();
        // Find the D-Bus object path for the WiFi device.
        let wifi_device_path = match get_wireless_device_path(&cn).await {
            Ok(path) => path,
            Err(e) => {
                error!("failed to get WiFi device path: {}", e);
                return Err(ProxyError::DbusCallFailed(format!(
                    "failed to get wireless device path: {}",
                    e
                )));
            }
        };

        // Validate the device path.
        let device = match ObjectPath::try_from(wifi_device_path) {
            Ok(path) => path,
            Err(e) => {
                error!("failed to convert device path: {}", e);
                return Err(ProxyError::InvalidDevicePath(format!("{}", e)));
            }
        };

        // Use the root object for the specific object (typically "/").
        let specific_object = ObjectPath::try_from("/").unwrap();
        let mut connection = HashMap::new();

        // Build the "connection" settings.
        let mut connection_connection = HashMap::new();
        let binding = Value::from(&ssid);
        connection_connection.insert("id", &binding);
        let binding = Value::from("802-11-wireless");
        connection_connection.insert("type", &binding);
        let binding = Value::from(Uuid::new_v4().to_string());
        connection_connection.insert("uuid", &binding);
        connection.insert("connection", connection_connection);

        // Build the "802-11-wireless" settings.
        let mut connection_wireless = HashMap::new();
        let binding = Value::from(ssid.as_bytes().to_vec());
        connection_wireless.insert("ssid", &binding);
        let binding = Value::from("infrastructure");
        connection_wireless.insert("mode", &binding);
        connection.insert("802-11-wireless", connection_wireless);

        // Build the "802-11-wireless-security" settings if a password is provided.
        let mut connection_wireless_security = HashMap::new();
        let binding = Value::from("wpa-psk");
        connection_wireless_security.insert("key-mgmt", &binding);
        let binding = Value::from(password.unwrap_or(String::new()));
        connection_wireless_security.insert("psk", &binding);
        connection.insert("802-11-wireless-security", connection_wireless_security);

        // Set IPv4 to automatic configuration.
        let mut connection_ipv4 = HashMap::new();
        let binding = Value::from("auto");
        connection_ipv4.insert("method", &binding);
        connection.insert("ipv4", connection_ipv4);

        // Set IPv6 to ignore.
        let mut connection_ipv6 = HashMap::new();
        let binding = Value::from("ignore");
        connection_ipv6.insert("method", &binding);
        connection.insert("ipv6", connection_ipv6);

        // Add and activate the connection using the composed settings.
        match self
            .add_and_activate_connection(connection, &device, &specific_object)
            .await
        {
            Ok((new_connection_obj_path, active_connection_obj_path)) => Ok((
                new_connection_obj_path.to_string(),
                active_connection_obj_path.to_string(),
            )),
            Err(e) => {
                error!("failed to connect to network: {}", e);
                Err(ProxyError::DbusCallFailed(format!(
                    "failed to connect to network: {}",
                    e
                )))
            }
        }
    }

    /// Disconnect from the current wireless network.
    ///
    /// Note: This disables the wireless connection, but credentials remain saved.
    async fn disconnect(&self) -> Result<(), ProxyError> {
        let cn = self.0.connection();

        // Get the wireless device path.
        let device_path = match get_wireless_device_path(cn).await {
            Ok(path) => path,
            Err(e) => {
                return Err(e.into());
            }
        };

        // Create a proxy for the device.
        let device_proxy = match device::DeviceProxy::new(&cn, device_path).await {
            Ok(proxy) => proxy,
            Err(e) => {
                error!("failed to create device proxy: {}", e);
                return Err(ProxyError::ProxyCreationFailed(format!(
                    "failed to create device proxy: {}",
                    e
                )));
            }
        };

        // Request disconnection.
        match device_proxy.disconnect().await {
            Ok(res) => Ok(res),
            Err(e) => {
                return Err(ProxyError::DbusCallFailed(format!(
                    "failed to disconnect: {}",
                    e
                )));
            }
        }
    }
}

/// Helper function to find the D-Bus object path of the first WiFi device.
///
/// Returns the object path as a String or an error if no WiFi device is found.
async fn get_wireless_device_path(cn: &Connection) -> Result<String, ProxyError> {
    info!("getting WiFi device path...");
    // Create a proxy to NetworkManager.
    let proxy = match NetworkManagerProxy::new(&cn).await {
        Ok(proxy) => proxy,
        Err(e) => {
            error!("failed to create NetworkManager proxy: {}", e);
            return Err(ProxyError::ProxyCreationFailed(format!(
                "failed to create NetworkManager proxy: {}",
                e
            )));
        }
    };

    // Get all devices.
    let devices = match proxy.get_all_devices().await {
        Ok(devices) => devices,
        Err(e) => {
            error!("failed to get devices: {}", e);
            return Err(ProxyError::DbusCallFailed(format!(
                "failed to get devices: {}",
                e
            )));
        }
    };
    trace!("found {} devices", devices.len());

    // Iterate and return the path of the first WiFi device (type == WIFI_DEVICE_TYPE).
    for device in devices {
        let device_proxy = match device::DeviceProxy::new(&cn, device.clone()).await {
            Ok(proxy) => proxy,
            Err(e) => {
                error!("failed to create device proxy: {}", e);
                continue;
            }
        };

        match device_proxy.device_type().await {
            Ok(device_type) => {
                if device_type == WIFI_DEVICE_TYPE {
                    info!("found WiFi device: {}", device);
                    return Ok(device.to_string());
                }
            }
            Err(e) => {
                error!("failed to get device type: {}", e);
                continue;
            }
        }
    }
    Err(ProxyError::NoWifiDeviceFound.into())
}
