[package]
name = "sources"
description = "Searches across user-defined/external sources"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
tokio = { workspace = true }
notify = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
zbus = { workspace = true }
dirs = { version = "6.0.0" }
tantivy = { git = "https://github.com/quickwit-oss/tantivy.git", branch = "main" }
