
[package]
name = "mechanix-launcher"
description = "Launcher application"
edition = "2024"
version = "0.0.3"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
gpui = { workspace = true }
commons = { path = "../commons" }
settings = { path = "../settings" }
theme = { path = "../theme" }
status_bar = { path = "../status_bar" }
power_options = { path = "../power_options" }
settings_drawer = { path = "../settings_drawer" }
universal_search = { path = "../universal_search" }
running_apps = { path = "../running_apps" }
notifications = { path = "../notifications" }
homescreen = { path = "../homescreen" }
dispatcher = { path = "../dispatcher" }
shell_state = { path = "../shell_state" }
volume_slider = { path = "../volume_slider" }
hardware_buttons = { path = "../hardware_buttons" }
lockscreen = { path = "../lockscreen" }
icons = { path = "../icons" }

[package.metadata.deb]
maintainer = "Akshay Raina <akshayr@mechasystems.com>"
extended-description = """\
Launcher application."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    # target/release path is special, and gets replaced by cargo-deb with the actual target dir path.
    [
        "../../../target/release/mechanix-launcher",
        "usr/bin/",
        "755",
    ],
    [
        "../../../assets/icons.example.toml",
        "etc/mechanix/shell/assets/icons.toml",
        "755",
    ],
    [
        "../../../assets/settings.example.toml",
        "etc/mechanix/shell/assets/settings.toml",
        "755",
    ],
    [
        "../../../assets/icons/app-drawer/*",
        "usr/share/mechanix/shell/assets/icons/app-drawer/",
        "755",
    ],
    [
        "../../../assets/icons/running-apps/*",
        "usr/share/mechanix/shell/assets/icons/running-apps/",
        "755",
    ],
    [
        "../../../assets/icons/settings-drawer/*",
        "usr/share/mechanix/shell/assets/icons/settings-drawer/",
        "755",
    ],
    [
        "../../../assets/icons/status-bar/*",
        "usr/share/mechanix/shell/assets/icons/status-bar/",
        "755",
    ],
    [
        "../../../assets/icons/universal-search/*",
        "usr/share/mechanix/shell/assets/icons/universal-search/",
        "755",
    ],
    [
        "../../../assets/icons/notifications/*",
        "usr/share/mechanix/shell/assets/icons/notifications/",
        "755",
    ],
    [
        "../../../assets/icons/power-options/*",
        "usr/share/mechanix/shell/assets/icons/power-options/",
        "755",
    ],
    [
        "../../../assets/icons/lockscreen/*",
        "usr/share/mechanix/shell/assets/icons/lockscreen/",
        "755",
    ],
]

[package.metadata.generate-rpm]
summary = "Launcher application"
license = "MIT"                  # or workspace override if you have one
auto-req = "yes"

assets = [
    # Binary
    { source = "../../../target/release/mechanix-launcher", dest = "/usr/bin/mechanix-launcher", mode = "755" },

    # Icons loading file
    { source = "../../../assets/icons.example.toml", dest = "/etc/mechanix/shell/assets/icons.toml", mode = "755" },

    # Settings file
    { source = "../../../assets/settings.example.toml", dest = "/etc/mechanix/shell/assets/settings.toml", mode = "755" },

    # App drawer icons
    { source = "../../../assets/icons/app-drawer/*", dest = "/usr/share/mechanix/shell/assets/icons/app-drawer/", mode = "755" },

    # Running apps icons
    { source = "../../../assets/icons/running-apps/*", dest = "/usr/share/mechanix/shell/assets/icons/running-apps/", mode = "755" },

    # Settings drawer icons
    { source = "../../../assets/icons/settings-drawer/*", dest = "/usr/share/mechanix/shell/assets/icons/settings-drawer/", mode = "755" },


    # Status bar icons
    { source = "../../../assets/icons/status-bar/*", dest = "/usr/share/mechanix/shell/assets/icons/status-bar/", mode = "755" },

    # Universal search icons
    { source = "../../../assets/icons/universal-search/*", dest = "/usr/share/mechanix/shell/assets/icons/universal-search/", mode = "755" },

    # Notifications icons
    { source = "../../../assets/icons/notifications/*", dest = "/usr/share/mechanix/shell/assets/icons/notifications/", mode = "755" },

    # Power options icons
    { source = "../../../assets/icons/power-options/*", dest = "/usr/share/mechanix/shell/assets/icons/power-options/", mode = "755" },

    # Lockscreen icons
    { source = "../../../assets/icons/lockscreen/*", dest = "/usr/share/mechanix/shell/assets/icons/lockscreen/", mode = "755" },


]
