[package]
name = "mechanix-notification"
description = "Notification application"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
mxconf_dbus = { workspace = true }

[package.metadata.deb]
maintainer = "Akshay Raina <akshayr@mechasystems.com>"
changelog = "debian/changelog"
extended-description = """\
Notification application."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    # target/release path is special, and gets replaced by cargo-deb with the actual target dir path.
    [
        "../../../target/release/mechanix-notification",
        "usr/bin/",
        "755",
    ],
]
