[package]
name = "notifications"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
gpui = { workspace = true }
futures = { workspace = true }
desktop_dbus = { path = "../../../dbus/mechanix/desktop"}
commons = { path = "../commons"}
settings = { path = "../settings"}
theme = { path = "../theme" }
smol = "2.0.2"
uuid = "1.18.1"
regex = "1.11.3"